# DEVELOPMENT PROFILE

# DATASOURCE
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cyberas
quarkus.datasource.username=cyberas
quarkus.datasource.password=cyberas_dev_password

# HIBERNATE
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# REDIS
quarkus.redis.hosts=redis://localhost:6379

# LOGGING
quarkus.log.level=DEBUG
quarkus.log.console.level=DEBUG
